version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80"
    depends_on:
      - infinite-butts
      - protobooth
      
  infinite-butts:
    image: jumpmyman/butts-prompts
    container_name: infinite-butts
    build:
      context: .
      dockerfile: ./ButtsBlazor/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"

  protobooth:
    image: jumpmyman/butts-prompts
    container_name: protobooth
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
    build:
      context: .
      dockerfile: ./ButtsBlazor/Dockerfile
    ports:
      - "8081"
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883"
    command: /usr/sbin/mosquitto -v -c /mosquitto/config/mosquitto.conf
    restart: unless-stopped

  espam:
    image: butts-prompts
    container_name: espam.vs
    env_file: ./espam.env
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: ../ButtsBlazor
      dockerfile: ./ButtsBlazor/Dockerfile
    ports:
      - "8080"
    restart: unless-stopped
