version: '3.4'

services:
  ngnix:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - infinite-butts
      - protobooth
  infinite-butts:
    volumes:
      - .\ButtsBlazor\wwwroot\butts_images:/app/wwwroot/butts_images
      - .\ButtsBlazor\db:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"

  protobooth:
    volumes:
      - ..\Protobooth\images:/app/wwwroot/butts_images
      - ..\Protobooth\db:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8081:8080"
