// <auto-generated />
using System;
using ButtsBlazor.Api.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ButtsBlazor.Api.Migrations
{
    [DbContext(typeof(ButtsDbContext))]
    [Migration("20240831214809_Added Metadata PK")]
    partial class AddedMetadataPK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ButtsBlazor.Api.Model.ImageEntity", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("RowId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ButtsBlazor.Api.Model.ImageMetadata", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.HasIndex("ImageEntityId");

                    b.ToTable("ImageMetadata");
                });

            modelBuilder.Entity("ButtsBlazor.Api.Model.PromptEntity", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArgsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CannyImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Enqueued")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessingCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessingStart")
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.HasIndex("ArgsId");

                    b.HasIndex("CannyImageId");

                    b.HasIndex("ControlImageId");

                    b.HasIndex("OutputImageId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("ButtsBlazor.Services.PromptArgs", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CannyHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CannyLow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFilePath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ControlScale")
                        .HasColumnType("REAL");

                    b.Property<int?>("ControlSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Negative")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumSteps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.ToTable("PromptArgs");
                });

            modelBuilder.Entity("Configuration.EFCore.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Application")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "Environment", "Application");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("ButtsBlazor.Api.Model.ImageMetadata", b =>
                {
                    b.HasOne("ButtsBlazor.Api.Model.ImageEntity", "ImageEntity")
                        .WithMany("ImageMetadata")
                        .HasForeignKey("ImageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageEntity");
                });

            modelBuilder.Entity("ButtsBlazor.Api.Model.PromptEntity", b =>
                {
                    b.HasOne("ButtsBlazor.Services.PromptArgs", "Args")
                        .WithMany()
                        .HasForeignKey("ArgsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ButtsBlazor.Api.Model.ImageEntity", "CannyImage")
                        .WithMany()
                        .HasForeignKey("CannyImageId");

                    b.HasOne("ButtsBlazor.Api.Model.ImageEntity", "ControlImage")
                        .WithMany()
                        .HasForeignKey("ControlImageId");

                    b.HasOne("ButtsBlazor.Api.Model.ImageEntity", "OutputImage")
                        .WithMany()
                        .HasForeignKey("OutputImageId");

                    b.Navigation("Args");

                    b.Navigation("CannyImage");

                    b.Navigation("ControlImage");

                    b.Navigation("OutputImage");
                });

            modelBuilder.Entity("ButtsBlazor.Api.Model.ImageEntity", b =>
                {
                    b.Navigation("ImageMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
